<a href="https://colab.research.google.com/github/adenadit/My-Data-Science-Site/blob/main/1_Multidimensional_Array_Object.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy ndarray : Multidimensional Array Object**

In [2]:
import numpy as np

In [3]:
my_array = np.arange(100)
print(my_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


>arange merupakan salahsatu fungsi dari numpy yang berfungsi untuk membuat kan array sebanyak masukan yang kita inginkan









In [4]:
my_list = list(range(100))
print(my_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


>list merupakan fungsi bawaan python yang memiliki fungsi serupa dengan arang namun dalam pengolahan array memiliki perbedaan dari arange

In [5]:
my_array2 = my_array * 2
print(my_array2)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142
 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178
 180 182 184 186 188 190 192 194 196 198]


In [7]:
my_list2 = my_list *2
print(my_list2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


> ketika dikalikan dengan angka 2 terlihat perbedaan antara arange dan list

 **1. Numpy ndarray : Multidimensional Array Object**

In [8]:
# membuat beberapa random data
data = np.random.randn(2,3)               # membuat random data sesuai dimensi yang dimasukan
print(data)

[[ 0.73364396 -0.53037759 -0.65971991]
 [-0.34523706  1.18883743 -0.69861627]]


In [9]:
# jika di berikan operasi matematika
data * 10

array([[ 7.33643961, -5.30377588, -6.59719907],
       [-3.45237059, 11.88837434, -6.9861627 ]])

In [10]:
data + data

array([[ 1.46728792, -1.06075518, -1.31943981],
       [-0.69047412,  2.37767487, -1.39723254]])

>setiap array pasti memiliki shape , indikasi tuple dan dtype

In [12]:
print(data.shape)

(2, 3)


In [13]:
print(data.dtype)

float64


*   **Creating ndarray**





In [14]:
data1 = [1,3,4.7,2,5,6]

In [15]:
arr1 = np.array(data1)

In [16]:
arr1

array([1. , 3. , 4.7, 2. , 5. , 6. ])

In [17]:
#Multidimensional Array
data2 = [[1,2,3,4],[5,6,7,8]]

In [18]:
arr2 = np.array(data2)

In [19]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

>arr2 memiliki 2 dimensi, sehingga dapat ditampilkan dimensi dan shape nya

In [22]:
arr2.ndim

2

In [23]:
arr2.shape

(2, 4)

In [24]:
#mengecek type data masing masing
arr1.dtype

dtype('float64')

In [25]:
arr2.dtype

dtype('int64')

>kemudian kita juga dapat membuat sebuah array zeros dan ones

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])