<a href="https://colab.research.google.com/github/adenadit/My-Data-Science-Site/blob/main/Numpy/Basic/1_Multidimensional_Array_Object.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy ndarray : Multidimensional Array Object**

In [1]:
import numpy as np

In [2]:
my_array = np.arange(100)
print(my_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


>arange merupakan salahsatu fungsi dari numpy yang berfungsi untuk membuat kan array sebanyak masukan yang kita inginkan









In [ ]:
my_list = list(range(100))
print(my_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


>list merupakan fungsi bawaan python yang memiliki fungsi serupa dengan arang namun dalam pengolahan array memiliki perbedaan dari arange

In [ ]:
my_array2 = my_array * 2
print(my_array2)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142
 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178
 180 182 184 186 188 190 192 194 196 198]


In [ ]:
my_list2 = my_list *2
print(my_list2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


> ketika dikalikan dengan angka 2 terlihat perbedaan antara arange dan list

 **1. Numpy ndarray : Multidimensional Array Object**

In [ ]:
# membuat beberapa random data
data = np.random.randn(2,3)               # membuat random data sesuai dimensi yang dimasukan
print(data)

[[ 0.73364396 -0.53037759 -0.65971991]
 [-0.34523706  1.18883743 -0.69861627]]


In [ ]:
# jika di berikan operasi matematika
data * 10

array([[ 7.33643961, -5.30377588, -6.59719907],
       [-3.45237059, 11.88837434, -6.9861627 ]])

In [ ]:
data + data

array([[ 1.46728792, -1.06075518, -1.31943981],
       [-0.69047412,  2.37767487, -1.39723254]])

>setiap array pasti memiliki shape , indikasi tuple dan dtype

In [ ]:
print(data.shape)

(2, 3)


In [ ]:
print(data.dtype)

float64


*   **Creating ndarray**





In [ ]:
data1 = [1,3,4.7,2,5,6]

In [ ]:
arr1 = np.array(data1)

In [ ]:
arr1

array([1. , 3. , 4.7, 2. , 5. , 6. ])

In [ ]:
#Multidimensional Array
data2 = [[1,2,3,4],[5,6,7,8]]

In [ ]:
arr2 = np.array(data2)

In [ ]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

>arr2 memiliki 2 dimensi, sehingga dapat ditampilkan dimensi dan shape nya

In [ ]:
arr2.ndim

2

In [ ]:
arr2.shape

(2, 4)

In [ ]:
#mengecek type data masing masing
arr1.dtype

dtype('float64')

In [ ]:
arr2.dtype

dtype('int64')

>kemudian kita juga dapat membuat sebuah array zeros dan ones

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

* **Data Types for ndarrays**



In [3]:
arr1 = np.array([1,2,3], dtype=np.float64)

In [5]:
arr2 = np.array([1,2,3], dtype=np.int32)

In [6]:
print(arr1.dtype)

float64


In [7]:
print(arr2.dtype)

int32


>dalam penerapannya terkadang kita ingin merubah tipe data yang digunakan
maka kita dapat menggunakan fungsi astype

In [8]:
arr3 = np.array([2,3,12])

In [9]:
print(arr3.dtype)

int64


In [10]:
#mengkonvert tipe data
float_arr3 = arr3.astype(np.float64)

In [11]:
print(float_arr3.dtype)
print(float_arr3)

float64
[ 2.  3. 12.]


>contoh lain kita ingin mengubah tipe data float ke int

In [12]:
arr4 = np.array([2.11, 3.14, 9.992, 16.2, 22.3])

In [14]:
int_arr4 = arr4.astype(np.int32)

In [16]:
print(int_arr4)
print(int_arr4.dtype)

[ 2  3  9 16 22]
int32


>begitupun konversi tipe data lainnya

* **Arithmatic with numpy arrays**

In [18]:
#untuk membuat array dengan beberapa kolom

arr5 = np.array([[1,2,3],[4,5,6]])

In [19]:
print(arr5)

[[1 2 3]
 [4 5 6]]


In [21]:
print(arr5*arr5)

[[ 1  4  9]
 [16 25 36]]


In [22]:
print(arr5-arr5)

[[0 0 0]
 [0 0 0]]


In [23]:
print(1/arr5)

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


In [24]:
print(arr5**0.5)

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [25]:
arr6 = np.array([[2,7,1],[5,6,2]])

In [26]:
print(arr5>arr6)

[[False False  True]
 [False False  True]]


* **Basic indexing and Slicing**

>dengan metode ini memungkinkan kita untuk memanggil nilai tertentu dalam suatu array

In [43]:
arr7 = np.array([12,24,16,67,83,90,25,55,17,24,83,27])

In [30]:
print(arr7[5])

90


In [31]:
print(arr7[0])

12


In [33]:
print(arr7[5:8])

[90 25 55]


>adapun jika kita menginginkan untuk mengganti satu atau beberapa nilai dari dalam suatu array maka dapat dilakukan dengan cara berikut

In [45]:
arr7[2:4]=23

In [46]:
print(arr7)

[12 24 23 23 83 90 25 55 17 24 83 27]


>selanjutnya kita mengenal istila slicing
dimana memungkinkan kita untu mengambil beberapa nilai dari suatu array dan kita pindahkan ke arrray lain


In [47]:
arr_slice = arr7[5:8]

In [49]:
print(arr_slice)

[90 25 55]


>namun jika menggunakan cara tersebut jika kita mengubah salahsatu nilai pada arr_slice maka nilai yang di ambil pada arr7 juga akan berubah

In [50]:
arr_slice[1]=39

In [51]:
print(arr7)
print(arr_slice)

[12 24 23 23 83 90 39 55 17 24 83 27]
[90 39 55]


>jika seandainya kita ingin mengambil data dari suatu array namun perubahan yang diberikan pada array baru tidak berdampak pada array lama maka selain menslice perlu tambahan function .copy
contoh = arr7[5:8].copy()

>kita juga bisa membuat suatu array dengan dimensi yang lebih besar

In [52]:
#array 2 dimensi
arr8 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [53]:
print(arr8)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [54]:
#pemanggilan nilai dalam suatu array 2d
print(arr8[2])

[7 8 9]


In [55]:
print(arr8[0][2])

3


In [57]:
print(arr8[0,2])

3
