<a href="https://colab.research.google.com/github/adenadit/My-Data-Science-Site/blob/main/Numpy/Basic/1_The_basics_of_Numpy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy Arrays Attributes**

In [2]:
import numpy as np

In [ ]:
x1 = np.random.randint(10, size=6)        #one-dimensional array
print(x1)

[3 5 2 4 7 6]


In [3]:
x2 = np.random.randint(10, size=(3,4))
print(x2)

[[3 2 0 8]
 [5 7 2 6]
 [9 9 5 8]]


In [ ]:
x3 = np.random.randint(10, size=(3,4,5))
print(x3)

[[[1 2 4 2 0]
  [3 2 0 7 5]
  [9 0 2 7 2]
  [9 2 3 3 2]]

 [[3 4 1 2 9]
  [1 4 6 8 2]
  [3 0 0 6 0]
  [6 3 3 8 8]]

 [[8 2 3 2 0]
  [8 8 3 8 2]
  [8 4 3 0 4]
  [3 6 9 8 0]]]


In [ ]:
print("x3 ndim : ", x3.ndim)      #the number of dimension
print("x3 shape : ", x3.shape)    #the size of dimension
print("x3 size : ", x3.size)      #the total size of the array

x3 ndim :  3
x3 shape :  (3, 4, 5)
x3 size :  60


In [ ]:
print("dtype : ", x3.dtype)       # the type of dimension

dtype :  int64


In [ ]:
print("item size : ", x3.itemsize, "bytes")       #list the size (in bytes)
print("nbytes : ", x3.nbytes, "bytes")            #total size (in bytes)

item size :  8 bytes
nbytes :  480 bytes


# **Array Indexing : Accessing Single Elements**

>**One-Dimensional List**

In [ ]:
print(x1)

[3 5 2 4 7 6]


In [ ]:
x1[0]

3

In [ ]:
x1[5]

6

In [ ]:
x1[-1]

6

In [ ]:
x1[-3]

4

>**Multi-Dimensional Listing**




In [ ]:
print(x2)

[[4 3 0 3]
 [5 0 2 3]
 [8 1 3 3]]


In [ ]:
x2[0,0]

4

In [ ]:
x2[1,2]

2

In [ ]:
x2[2,2]

3

>**modify Value**

In [ ]:
x2[0,0]=23

In [ ]:
print(x2)

[[23  3  0  3]
 [ 5  0  2  3]
 [ 8  1  3  3]]


namun perlu di perhatikan dalam modify value, Nilai yang diganti dengan nilai sebelumnya harus memiliki type data yang sama

# **Arrays Slicing : Accessing Subarrays**





```
# the Formula   x[start,stop,step]
```



>**One-Dimensional subarrays**

In [ ]:
x = np.arange(10)
print(x)

In [ ]:
x[:5]           #menampilkan 5 element pertama

array([0, 1, 2, 3, 4])

In [ ]:
x[5:]           #menampilkan 5 element terakhir

array([5, 6, 7, 8, 9])

In [ ]:
x[4:7]          #menampilkan elemen antara

array([4, 5, 6])

In [ ]:
x[::2]          #menampilkan elemen setiap nilai kelipatan

array([0, 2, 4, 6, 8])

In [ ]:
x[1::2]         #menampilkan elemen setiap nilai kelipatan, dimulai dari elemen 1

array([1, 3, 5, 7, 9])

In [ ]:
x[::-1]         #mereverse semua element

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
x[5::-2]        #reverse kelipatan dengan index 5

array([5, 3, 1])

>**Multi-Dimensional subarrays**

In [ ]:
print(x2)

[[23  3  0  3]
 [ 5  0  2  3]
 [ 8  1  3  3]]


In [ ]:
x2[:2,:3]           #2 row,3 column

array([[23,  3,  0],
       [ 5,  0,  2]])

In [ ]:
x2[:3,::2]          #menampilkan semua row, pada coloumn kelipatan 2

array([[23,  0],
       [ 5,  2],
       [ 8,  3]])

In [ ]:
x2[::-1,::-1]       #reverse row dan coloumn

array([[ 3,  3,  1,  8],
       [ 3,  2,  0,  5],
       [ 3,  0,  3, 23]])

>**Accessing array rows and columns**


In [4]:
print(x2[0,:])      #menampilkan semua pada row 2

[3 2 0 8]


In [ ]:
print(x2[0])        #bentuk lainnya

> **Subarrays as no-copy views**

In [5]:
print(x2)

[[3 2 0 8]
 [5 7 2 6]
 [9 9 5 8]]


In [7]:
x2_sub = x2[:2,:2]      #ekstrak x2 ke array 2x2
print(sub_x2)

[[3 2]
 [5 7]]


In [9]:
x2_sub[0,0] = 99         #modifikasi subarray
print(x2_sub)            # namun nilai dari array sumber juga ikut berubah

[[99  2]
 [ 5  7]]


> **Creating copies of arrays**

In [10]:
x2_sub_copy = x2[:2,:2].copy()
print(x2_sub_copy)

[[99  2]
 [ 5  7]]


In [11]:
x2_sub_copy[0,0]=23
print(x2_sub_copy)

[[23  2]
 [ 5  7]]
