<a href="https://colab.research.google.com/github/adenadit/My-Data-Science-Site/blob/main/Numpy/Basic/1_The_basics_of_Numpy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy Arrays Attributes**

In [ ]:
import numpy as np

In [ ]:
x1 = np.random.randint(10, size=6)        #one-dimensional array
print(x1)

[3 5 2 4 7 6]


In [ ]:
x2 = np.random.randint(10, size=(3,4))
print(x2)

[[3 2 0 8]
 [5 7 2 6]
 [9 9 5 8]]


In [ ]:
x3 = np.random.randint(10, size=(3,4,5))
print(x3)

[[[1 2 4 2 0]
  [3 2 0 7 5]
  [9 0 2 7 2]
  [9 2 3 3 2]]

 [[3 4 1 2 9]
  [1 4 6 8 2]
  [3 0 0 6 0]
  [6 3 3 8 8]]

 [[8 2 3 2 0]
  [8 8 3 8 2]
  [8 4 3 0 4]
  [3 6 9 8 0]]]


In [ ]:
print("x3 ndim : ", x3.ndim)      #the number of dimension
print("x3 shape : ", x3.shape)    #the size of dimension
print("x3 size : ", x3.size)      #the total size of the array

x3 ndim :  3
x3 shape :  (3, 4, 5)
x3 size :  60


In [ ]:
print("dtype : ", x3.dtype)       # the type of dimension

dtype :  int64


In [ ]:
print("item size : ", x3.itemsize, "bytes")       #list the size (in bytes)
print("nbytes : ", x3.nbytes, "bytes")            #total size (in bytes)

item size :  8 bytes
nbytes :  480 bytes


# **Array Indexing : Accessing Single Elements**

>**One-Dimensional List**

In [ ]:
print(x1)

[3 5 2 4 7 6]


In [ ]:
x1[0]

3

In [ ]:
x1[5]

6

In [ ]:
x1[-1]

6

In [ ]:
x1[-3]

4

>**Multi-Dimensional Listing**




In [ ]:
print(x2)

[[4 3 0 3]
 [5 0 2 3]
 [8 1 3 3]]


In [ ]:
x2[0,0]

4

In [ ]:
x2[1,2]

2

In [ ]:
x2[2,2]

3

>**modify Value**

In [ ]:
x2[0,0]=23

In [ ]:
print(x2)

[[23  3  0  3]
 [ 5  0  2  3]
 [ 8  1  3  3]]


namun perlu di perhatikan dalam modify value, Nilai yang diganti dengan nilai sebelumnya harus memiliki type data yang sama

# **Arrays Slicing : Accessing Subarrays**





```
# the Formula   x[start,stop,step]
```



>**One-Dimensional subarrays**

In [ ]:
x = np.arange(10)
print(x)

In [ ]:
x[:5]           #menampilkan 5 element pertama

array([0, 1, 2, 3, 4])

In [ ]:
x[5:]           #menampilkan 5 element terakhir

array([5, 6, 7, 8, 9])

In [ ]:
x[4:7]          #menampilkan elemen antara

array([4, 5, 6])

In [ ]:
x[::2]          #menampilkan elemen setiap nilai kelipatan

array([0, 2, 4, 6, 8])

In [ ]:
x[1::2]         #menampilkan elemen setiap nilai kelipatan, dimulai dari elemen 1

array([1, 3, 5, 7, 9])

In [ ]:
x[::-1]         #mereverse semua element

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
x[5::-2]        #reverse kelipatan dengan index 5

array([5, 3, 1])

>**Multi-Dimensional subarrays**

In [ ]:
print(x2)

[[23  3  0  3]
 [ 5  0  2  3]
 [ 8  1  3  3]]


In [ ]:
x2[:2,:3]           #2 row,3 column

array([[23,  3,  0],
       [ 5,  0,  2]])

In [ ]:
x2[:3,::2]          #menampilkan semua row, pada coloumn kelipatan 2

array([[23,  0],
       [ 5,  2],
       [ 8,  3]])

In [ ]:
x2[::-1,::-1]       #reverse row dan coloumn

array([[ 3,  3,  1,  8],
       [ 3,  2,  0,  5],
       [ 3,  0,  3, 23]])

>**Accessing array rows and columns**


In [ ]:
print(x2[0,:])      #menampilkan semua pada row 2

[3 2 0 8]


In [ ]:
print(x2[0])        #bentuk lainnya

> **Subarrays as no-copy views**

In [ ]:
print(x2)

[[3 2 0 8]
 [5 7 2 6]
 [9 9 5 8]]


In [ ]:
x2_sub = x2[:2,:2]      #ekstrak x2 ke array 2x2
print(sub_x2)

[[3 2]
 [5 7]]


In [ ]:
x2_sub[0,0] = 99         #modifikasi subarray
print(x2_sub)            # namun nilai dari array sumber juga ikut berubah

[[99  2]
 [ 5  7]]


> **Creating copies of arrays**

In [ ]:
x2_sub_copy = x2[:2,:2].copy()
print(x2_sub_copy)

[[99  2]
 [ 5  7]]


In [ ]:
x2_sub_copy[0,0]=23
print(x2_sub_copy)

[[23  2]
 [ 5  7]]


# **Reshaping of Arrays**




In [ ]:
grid = np.arange(1,10).reshape((3,3))       #berfungsi mengubah nilai yang dimasukan menjadi shape yang diinginkan
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
x4 = np.array([1,2,3])            #vektor baris via reshape
x4.reshape((1,3))

array([[1, 2, 3]])

In [ ]:
x4[np.newaxis,:]                  #vektor baris via newaxis

array([[1, 2, 3]])

In [ ]:
# colomn vektor via reshape
x4.reshape((3,1))

array([[1],
       [2],
       [3]])

In [ ]:
#colomn vektor via newaxis
x4[:,np.newaxis]

array([[1],
       [2],
       [3]])

# **Array Concatenation and Splitting**




merupakan metode menggabungkan dua array

> **Concatenation of arrays**

In [23]:
xc = np.array([1, 2, 3])
yc = np.array([4, 5, 6])

np.concatenate([xc, yc])

array([1, 2, 3, 4, 5, 6])

In [24]:
zc= [23, 23, 23]                      # kita dapat menggabungkan beberapa array dengan np.concatenate
print(np.concatenate([xc, yc, zc]))

[ 1  2  3  4  5  6 23 23 23]


In [27]:
#np.concatenate juga dapat dipakai pada array 2-dimensi
gridc = np.array([[1,2,3],
                  [4,5,6]])

np.concatenate([gridc,gridc])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [29]:
np.concatenate([gridc, gridc], axis=1)            # concate dengan index 1


array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

untuk bekerja pada pencampuran dimensi array, ita mesti menggunakan np.vstack (vertical stack) dan np.hstack(horizontal stack)

In [33]:
xs = np.array([1, 2, 3])              #berfungsi mengabungkan array secara vertical
grids = np.array([[4, 5, 6],
                  [7, 8, 9]])

np.vstack([xs, grids])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
ys = np.array([[23],
               [23]])

np.hstack([grids,ys])

array([[ 4,  5,  6, 23],
       [ 7,  8,  9, 23]])

gunakan np.dstack jika pada array 3 axis

> **Splitting of arrays**

In [48]:
xsp = [1, 2, 3, 23, 23, 3, 2, 1]
xsp1, xsp2, xsp3 = np.split(xsp,[3,5])

print(xsp1, xsp2, xsp3)

[1 2 3] [23 23] [3 2 1]


np.hsplit dan np.vsplit

In [50]:
gridsp = np.arange(16).reshape((4, 4))
print(gridsp)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [55]:
upper, lower = np.vsplit(gridsp, [2])         # penerapan np.vsplit

In [56]:
print(upper)

[[0 1 2 3]
 [4 5 6 7]]


In [57]:
print(lower)

[[ 8  9 10 11]
 [12 13 14 15]]


In [62]:
left, right = np.hsplit(gridsp, [2])

In [63]:
print(left)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]


In [64]:
print(right)

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
