<a href="https://colab.research.google.com/github/adenadit/My-Data-Science-Site/blob/main/Numpy/Basic/1_The_basics_of_Numpy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy Arrays Attributes**

In [1]:
import numpy as np

In [5]:
x1 = np.random.randint(10, size=6)        #one-dimensional array
print(x1)

[3 5 2 4 7 6]


In [11]:
x2 = np.random.randint(10, size=(3,4))
print(x2)

[[4 3 0 3]
 [5 0 2 3]
 [8 1 3 3]]


In [13]:
x3 = np.random.randint(10, size=(3,4,5))
print(x3)

[[[1 2 4 2 0]
  [3 2 0 7 5]
  [9 0 2 7 2]
  [9 2 3 3 2]]

 [[3 4 1 2 9]
  [1 4 6 8 2]
  [3 0 0 6 0]
  [6 3 3 8 8]]

 [[8 2 3 2 0]
  [8 8 3 8 2]
  [8 4 3 0 4]
  [3 6 9 8 0]]]


In [14]:
print("x3 ndim : ", x3.ndim)      #the number of dimension
print("x3 shape : ", x3.shape)    #the size of dimension
print("x3 size : ", x3.size)      #the total size of the array

x3 ndim :  3
x3 shape :  (3, 4, 5)
x3 size :  60


In [15]:
print("dtype : ", x3.dtype)       # the type of dimension

dtype :  int64


In [16]:
print("item size : ", x3.itemsize, "bytes")       #list the size (in bytes)
print("nbytes : ", x3.nbytes, "bytes")            #total size (in bytes)

item size :  8 bytes
nbytes :  480 bytes


# **Array Indexing : Accessing Single Elements**

>**One-Dimensional List**

In [17]:
print(x1)

[3 5 2 4 7 6]


In [18]:
x1[0]

3

In [19]:
x1[5]

6

In [20]:
x1[-1]

6

In [21]:
x1[-3]

4

>**Multi-Dimensional Listing**




In [22]:
print(x2)

[[4 3 0 3]
 [5 0 2 3]
 [8 1 3 3]]


In [24]:
x2[0,0]

4

In [25]:
x2[1,2]

2

In [27]:
x2[2,2]

3

>**modify Value**

In [28]:
x2[0,0]=23

In [29]:
print(x2)

[[23  3  0  3]
 [ 5  0  2  3]
 [ 8  1  3  3]]


namun perlu di perhatikan dalam modify value, Nilai yang diganti dengan nilai sebelumnya harus memiliki type data yang sama

# **Arrays Slicing : Accessing Subarrays**





```
# the Formula   x[start,stop,step]
```



>**One-Dimensional subarrays**

In [30]:
x = np.arange(10)
print(x)

In [34]:
x[:5]           #menampilkan 5 element pertama

array([0, 1, 2, 3, 4])

In [35]:
x[5:]           #menampilkan 5 element terakhir

array([5, 6, 7, 8, 9])

In [36]:
x[4:7]          #menampilkan elemen antara

array([4, 5, 6])

In [40]:
x[::2]          #menampilkan elemen setiap nilai kelipatan

array([0, 2, 4, 6, 8])

In [41]:
x[1::2]         #menampilkan elemen setiap nilai kelipatan, dimulai dari elemen 1

array([1, 3, 5, 7, 9])

In [42]:
x[::-1]         #mereverse semua element

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [44]:
x[5::-2]        #reverse kelipatan dengan index 5

array([5, 3, 1])

>**Multi-Dimensional subarrays**

In [45]:
print(x2)

[[23  3  0  3]
 [ 5  0  2  3]
 [ 8  1  3  3]]


In [46]:
x2[:2,:3]           #2 row,3 column

array([[23,  3,  0],
       [ 5,  0,  2]])

In [47]:
x2[:3,::2]          #menampilkan semua row, pada coloumn kelipatan 2

array([[23,  0],
       [ 5,  2],
       [ 8,  3]])

In [48]:
x2[::-1,::-1]       #reverse row dan coloumn

array([[ 3,  3,  1,  8],
       [ 3,  2,  0,  5],
       [ 3,  0,  3, 23]])

>**Accessing array rows and columns**
